// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2a9md3bvjNTBJg0r5xocHQVzYSM_98PA',
    appId: '1:748860715146:web:310dc5b35c42456878fd73',
    messagingSenderId: '748860715146',
    projectId: 'rugby-score-65107',
    authDomain: 'rugby-score-65107.firebaseapp.com',
    storageBucket: 'rugby-score-65107.firebasestorage.app',
    measurementId: 'G-0NF5Q8RQS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9ynj524ACn5C9MAiT-52O2EkuBzZDV50',
    appId: '1:748860715146:android:630749cc9a76e6a278fd73',
    messagingSenderId: '748860715146',
    projectId: 'rugby-score-65107',
    storageBucket: 'rugby-score-65107.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzgKosBN53OCuV2gH1tgoSaQf4TS28nWU',
    appId: '1:748860715146:ios:9b0a868bc15363cd78fd73',
    messagingSenderId: '748860715146',
    projectId: 'rugby-score-65107',
    storageBucket: 'rugby-score-65107.firebasestorage.app',
    iosBundleId: 'com.example.rugbyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzgKosBN53OCuV2gH1tgoSaQf4TS28nWU',
    appId: '1:748860715146:ios:9b0a868bc15363cd78fd73',
    messagingSenderId: '748860715146',
    projectId: 'rugby-score-65107',
    storageBucket: 'rugby-score-65107.firebasestorage.app',
    iosBundleId: 'com.example.rugbyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2a9md3bvjNTBJg0r5xocHQVzYSM_98PA',
    appId: '1:748860715146:web:55980f93d44b7f3a78fd73',
    messagingSenderId: '748860715146',
    projectId: 'rugby-score-65107',
    authDomain: 'rugby-score-65107.firebaseapp.com',
    storageBucket: 'rugby-score-65107.firebasestorage.app',
    measurementId: 'G-QDT520ND9V',
  );
}
